### ISSUE TITLE
Internal variable shown in rofi output

### ISSUE THREAD

**Issue by mchwalisz** [miphreal/python-rofi-menu#3]
Since latest updates, I have a problem in rofi_menu where the last internal variable hash is shown in the rofi menu list.

![2020-09-26-144045_5520x2160_scrot](https://user-images.githubusercontent.com/2182186/94341018-6fc64280-0006-11eb-91a2-5768351d23b6.png)

My suspicion is the missing end line character on the output, but cannot figure out where to fix it.

```
Version: 1.6.0-9-g6ba878e4 (makepkg)
```

**Comment by miphreal** [comment]
Hey @mchwalisz, thanks for reporting this issue! tbh, I missed that a new version came out.

I'll have a look at what's new in 1.6 and will try to fix it.

**Comment by miphreal** [comment]
The issue was fixed. The recent changes (0.5.1) should work with the most recent version of rofi (1.6.1)
