### ISSUE TITLE
Any stdout becomes part of the menu

### ISSUE THREAD

**Issue by safijari** [miphreal/python-rofi-menu#4]
So, I have an import that I'm using to make my menu which prints some stuff, and looks like the lines it prints become menu items. If I forcibly suppress this output then things are fine.

Is there already a way to fix this? If not can you guide me as to where in this repo the issue might be coming into play? I can try to patch it.

**Comment by miphreal** [comment]
@safijari, can you please share more details about the issue, e.g.
- _rofi_ version
- _rofi-menu_ version
- _python_ version 
- example of the code you are trying to run 
- the command you use to run rofi
- the output you see and what you expect to see

**Comment by miphreal** [comment]
_Closing this issue as the issue itself is not clear_

Leaving it here for documentation purpose:

1. any text written to `sys.stdout` becomes a part of rofi menu (given the way rofi script mode works -- Rofi calls the script and expects it to output a menu into stdout)
2. any text written to `sys.stderr` is ignored by Rofi, so `sys.stderr` may be used to print any debug information and it won't be a part of menu
